#!/usr/bin/bash

#######################################################
# Place this file in ~/.local/share/nautilus/scripts/ #
# and make it executable.                             #
# This script is meant to run an AppImage inside a    #
# Distrobox container.                                #
# Useful for immurtable distros without AppImage      #
# support.                                            #
# You setup a dsitrobox container and install         #
# everything required for AppImages into it           #
#######################################################

CONTAINER_NAME=appimage
DIR="$(dirname "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}")"
FILE="$(basename "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}")"
chmod +x ${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}

(
echo "# Updateing appimage container"
(exec /usr/bin/distrobox-upgrade $CONTAINER_NAME)
echo "100"
) |
zenity --progress --title="Warming up" --text="Starting appimage container" --percentage=0 --auto-close

# Start bash in the directory the AppImage is located and then executes it.
# Some AppImages do not run with absolute paths
(exec /usr/bin/distrobox-enter -n $CONTAINER_NAME -- bash -c "cd ${DIR}; ./${FILE}")

zenity --question --text="AppImage terminated do you want to shutdown the container?"
case $? in
	0)
	(exec /usr/bin/distrobox-stop $CONTAINER_NAME)
	;;
esac
