#!/usr/bin/bash

#######################################################
# Place this file in ~/.local/share/nautilus/scripts/ #
# and make it executable.                             #
# This script is meant to run an AppImage inside a    #
# Distrobox container.                                #
# Useful for immurtable distros without AppImage      #
# support.                                            #
# You setup a dsitrobox container and install         #
# everything required for AppImages into it           #
#######################################################

CONTAINER_NAME=appimage
DIR="$(dirname "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}")"
FILE="$(basename "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}")"
chmod +x "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}"
(exec /usr/bin/distrobox-upgrade $CONTAINER_NAME)

if [ -z "${CONTAINER_ID}" ]; then
	# Start bash in the directory the AppImage is located and then executes it.
	# Some AppImages do not run with absolute paths
	(exec /usr/bin/distrobox-enter -n $CONTAINER_NAME -- bash -c "cd ${DIR}; ./${FILE}")
	(exec /usr/bin/distrobox-stop $CONTAINER_NAME)
else
	(exec "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}")
fi
